pimcore:
    properties:
        predefined:
            definitions:
                527fb0b5-0567-4422-b564-2c46230ea49f:
                    name: null
                    description: null
                    key: null
                    type: null
                    data: null
                    config: null
                    ctype: null
                    inheritable: false
                    creationDate: 1713454224
                    modificationDate: 1713454224
